apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: blog-app-pdb
spec:
  minAvailable: 2
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
spec:
  minAvailable: 1
