apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
        - name: fix-perms
          image: busybox:1.36
          command: ["sh","-c","chown -R 999:999 /var/lib/postgresql/data || true"]
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
