apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-app-dev
resources:
  - ../../base
  - namespace.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: blog
      app.kubernetes.io/managed-by: kustomize
      env: dev

patchesStrategicMerge:
  - patches/app-deployment-patch.yaml
  - patches/postgres-deployment-patch.yaml
  - patches/app-ingress-patch.yaml
